server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: scott
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  redis:
    database: 0
    host: 192.168.188.128
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 5000
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  devtools:
    restart:
      additional-paths: src/main/java
#  security:
#    user:
#      name: admin
#      password: 123
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/gtmap/fundsupervision/mapper/*.xml
logging:
  level:
    com:
      gtmap: debug
